{% set version = "0.2.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rlistings
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rlistings_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rlistings/rlistings_{{ version }}.tar.gz
  sha256: 99eb60c3b39f2667895ed54e58547c9ffb0d48ea509bab288488645da038b58a

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.1.0
    - r-formatters >=0.5.11
    - r-tibble >=2.0.0
  run:
    - r-base
    - r-checkmate >=2.1.0
    - r-formatters >=0.5.11
    - r-tibble >=2.0.0

test:
  commands:
    - $R -e "library('rlistings')"           # [not win]
    - "\"%R%\" -e \"library('rlistings')\""  # [win]

about:
  home: https://insightsengineering.github.io/rlistings/, https://github.com/insightsengineering/rlistings/
  license: Apache-2.0
  summary: Listings are often part of the submission of clinical trial data in regulatory settings.  We provide a framework for the specific formatting features often used when displaying large datasets in that context.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
